### ISSUE TITLE
curl to fetch portworx-sysvinit.sh results in HTTP 301

### ISSUE THREAD

**Issue by ben5556** [portworx/pxdocs#139]
Hi,

Step 2.3, the below link, in the documentation https://2.0.docs.portworx.com/install-with-other/ecs/ gives a HTTP 301.

sudo curl https://docs.portworx.com/cloud/aws/portworx-sysvinit.sh -o /etc/rc.d/init.d/portworx

Can this be fixed please ? Can I get a copy of the portworx-sysvinit.sh ASAP please as we are keen to try portworx for our workload ?

**Comment by harsh-px** [comment]
@ben5556 we have just pushed a fix and this will go live in 5-6 minutes. Sorry for the trouble.

**Comment by ben5556** [comment]
Thanks for quick response. Appreciate it.
